version: "3.8"
services: 
  database: 
    image: postgres
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres

  development:
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
